# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Check
        run: |
          system("git diff --name-only origin/master HEAD | grep Rmd > changes")
          for(i in system("cat changes", intern = TRUE)) {
          knitr::knit2html(i)
          }
        shell: Rscript {0}
