# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: r-lib/actions/setup-r@v1
      - uses: actions/cache@v1
        with:
          path: ~/Library/Application Support/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
             ${{ runner.os }}-renv-
      - name: Install dependencies
        run: |
          install.packages("renv")
          system('git log --grep="Merge pull request #[0-9]\\+" --pretty=oneline -2 | sed "s/ .*//g" > last_merge')
          system('while read line; do git diff --name-only "$line" HEAD; done < last_merge > changes')
          system('while read line; do grep "library(" "$line"; done < changes | sed -E  "s/.*library\\(|\\).*//g" > 1')
          system('while read line; do grep -E ".*\\:\\:" "$line"; done < changes | sed -E "s/\\:\\:.*//g" | sed -E "s/.*[^A-Za-z1-9]//g" > 2')
          renv::restore(packages = system('cat 1 2 | awk "NF" | sort -u', intern = TRUE))
        shell: Rscript {0}
      - name: Check
        run: |
          for(i in system("cat changes", intern = TRUE)) {
          knitr::knit2html(i)
          }
        shell: Rscript {0}
